name: CI
on: push
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.80.0"

      - name: Build
        # remove --minify tag if you do not need it
        # docs: https://gohugo.io/hugo-pipes/minification/
        run: hugo

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@main
        with:
          args: deploy --only hosting
          publish_dir: ./public
          publish_branch: main
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        #   cname: example.com